/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Daniel Zhabotinsky (https://sketchfab.com/DanielZhabotinsky)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-touge-racer-low-poly-model-59a0eaaa2af144b2956957e7032d0221
Title: Japanese Touge Racer - Low poly model
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    suspension_front_ae_bottom_0: THREE.Mesh
    suspension_front_ae_coil_0: THREE.Mesh
    suspension_rear_ae_bottom_0: THREE.Mesh
    backlight_left_ae_bottom_0: THREE.Mesh
    backlight_left_ae_headlights_0: THREE.Mesh
    headlight_left_ae_bottom_0: THREE.Mesh
    headlight_left_ae_glass_0: THREE.Mesh
    headlight_left_ae_headlights_0: THREE.Mesh
    headlight_left_ae_body_0: THREE.Mesh
    fender_left_ae_body_0: THREE.Mesh
    fender_left_ae_body_secondary_0: THREE.Mesh
    fender_left_ae_bottom_0: THREE.Mesh
    fender_left_ae_headlights_0: THREE.Mesh
    body_ae_body_0: THREE.Mesh
    body_ae_body_secondary_0: THREE.Mesh
    ['body_Material_#1595_0']: THREE.Mesh
    body_ae_bottom_0: THREE.Mesh
    body_ae_doorshut_0: THREE.Mesh
    body_ae_interior_0: THREE.Mesh
    body_ae_glass_0: THREE.Mesh
    ['body_Material_#2061_0']: THREE.Mesh
    bumper_rear_ae_bottom_0: THREE.Mesh
    bumper_rear_ae_body_0: THREE.Mesh
    hood_ae_body_0: THREE.Mesh
    hood_ae_doorshut_0: THREE.Mesh
    trunk_door_ae_body_0: THREE.Mesh
    trunk_door_ae_doorshut_0: THREE.Mesh
    trunk_door_ae_bottom_0: THREE.Mesh
    trunk_door_ae_glass_0: THREE.Mesh
    ['trunk_door_Material_#2062_0']: THREE.Mesh
    bumper_front_ae_bottom_0: THREE.Mesh
    bumper_front_ae_body_0: THREE.Mesh
    bumper_front_ae_headlights_0: THREE.Mesh
    ['bumper_front_Material_#2061_0']: THREE.Mesh
    door_left_ae_bottom_0: THREE.Mesh
    door_left_ae_interior_0: THREE.Mesh
    door_left_ae_body_secondary_0: THREE.Mesh
    door_left_ae_doorshut_0: THREE.Mesh
    door_left_ae_glass_0: THREE.Mesh
    door_left_ae_body_0: THREE.Mesh
    wheel_front_left_ae_tier_0: THREE.Mesh
    wheel_front_left_ae_rim_colour_0: THREE.Mesh
    headlight_right_ae_bottom_0: THREE.Mesh
    headlight_right_ae_glass_0: THREE.Mesh
    headlight_right_ae_headlights_0: THREE.Mesh
    headlight_right_ae_body_0: THREE.Mesh
    fender_right_ae_body_0: THREE.Mesh
    fender_right_ae_body_secondary_0: THREE.Mesh
    fender_right_ae_bottom_0: THREE.Mesh
    fender_right_ae_headlights_0: THREE.Mesh
    backlight_right_ae_bottom_0: THREE.Mesh
    backlight_right_ae_headlights_0: THREE.Mesh
    brakedisk_front_left_brakes_1s_0: THREE.Mesh
    brakedisk_front_right_brakes_1s_0: THREE.Mesh
    wheel_front_right_ae_tier_0: THREE.Mesh
    wheel_front_right_ae_rim_colour_0: THREE.Mesh
    door_right_ae_bottom_0: THREE.Mesh
    door_right_ae_interior_0: THREE.Mesh
    door_right_ae_body_secondary_0: THREE.Mesh
    door_right_ae_doorshut_0: THREE.Mesh
    door_right_ae_glass_0: THREE.Mesh
    door_right_ae_body_0: THREE.Mesh
    brakedisk_rear_right_brakes_1s_0: THREE.Mesh
    wheel_rear_right_ae_tier_0: THREE.Mesh
    wheel_rear_right_ae_rim_colour_0: THREE.Mesh
    brakedisk_rear_left_brakes_1s_0: THREE.Mesh
    wheel_rear_left_ae_tier_0: THREE.Mesh
    wheel_rear_left_ae_rim_colour_0: THREE.Mesh
    ['GRILL_11_-_Default_0']: THREE.Mesh
    ['Object001_Material_#2062_0']: THREE.Mesh
    Object003_ae_bottom_0: THREE.Mesh
  }
  materials: {
    ae_bottom: THREE.MeshPhysicalMaterial
    ae_coil: THREE.MeshStandardMaterial
    ae_headlights: THREE.MeshPhysicalMaterial
    ae_glass: THREE.MeshPhysicalMaterial
    ae_body: THREE.MeshStandardMaterial
    ae_body_secondary: THREE.MeshPhysicalMaterial
    Material_1595: THREE.MeshStandardMaterial
    ae_doorshut: THREE.MeshPhysicalMaterial
    ae_interior: THREE.MeshPhysicalMaterial
    Material_2061: THREE.MeshStandardMaterial
    Material_2062: THREE.MeshPhysicalMaterial
    ae_tier: THREE.MeshPhysicalMaterial
    ae_rim_colour: THREE.MeshPhysicalMaterial
    brakes_1s: THREE.MeshStandardMaterial
    ['11_-_Default']: THREE.MeshStandardMaterial
  }
}

export function Car(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/ae86.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="6c0520ed5ba444f79d9feee4fbed246efbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="RootNode">
              <group name="suspension_front" position={[-53.653, 22.216, 31.885]} scale={0.011}>
                <group name="Object_4" position={[2453.345, -756.102, 576.748]}>
                  <mesh
                    name="suspension_front_ae_bottom_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.suspension_front_ae_bottom_0.geometry}
                    material={materials.ae_bottom}
                  />
                  <mesh
                    name="suspension_front_ae_coil_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.suspension_front_ae_coil_0.geometry}
                    material={materials.ae_coil}
                  />
                </group>
              </group>
              <group name="suspension_rear" position={[40.664, 17.465, 31.932]} scale={0.013}>
                <group name="Object_8" position={[526.856, -415.445, 266.428]}>
                  <mesh
                    name="suspension_rear_ae_bottom_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.suspension_rear_ae_bottom_0.geometry}
                    material={materials.ae_bottom}
                  />
                </group>
              </group>
              <group name="backlight_left" position={[79.037, 29.342, 49.585]} scale={1.038}>
                <group name="Object_11" position={[-112.804, 1.925, 12.459]}>
                  <mesh
                    name="backlight_left_ae_bottom_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.backlight_left_ae_bottom_0.geometry}
                    material={materials.ae_bottom}
                  />
                  <mesh
                    name="backlight_left_ae_headlights_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.backlight_left_ae_headlights_0.geometry}
                    material={materials.ae_headlights}
                  />
                </group>
              </group>
              <group
                name="headlight_left"
                position={[-72.454, 27.98, 49.406]}
                rotation={[0, 0, -1.588]}>
                <group name="Object_15" position={[37.874, 4.577, 12.512]}>
                  <mesh
                    name="headlight_left_ae_bottom_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.headlight_left_ae_bottom_0.geometry}
                    material={materials.ae_bottom}
                  />
                  <mesh
                    name="headlight_left_ae_glass_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.headlight_left_ae_glass_0.geometry}
                    material={materials.ae_glass}
                  />
                  <mesh
                    name="headlight_left_ae_headlights_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.headlight_left_ae_headlights_0.geometry}
                    material={materials.ae_headlights}
                  />
                  <mesh
                    name="headlight_left_ae_body_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.headlight_left_ae_body_0.geometry}
                    material={materials.ae_body}
                  />
                </group>
              </group>
              <group name="fender_left" position={[-50.498, 22.532, 58.196]}>
                <group name="Object_21" position={[16.856, 8.655, 3.925]}>
                  <mesh
                    name="fender_left_ae_body_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.fender_left_ae_body_0.geometry}
                    material={materials.ae_body}
                  />
                  <mesh
                    name="fender_left_ae_body_secondary_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.fender_left_ae_body_secondary_0.geometry}
                    material={materials.ae_body_secondary}
                  />
                  <mesh
                    name="fender_left_ae_bottom_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.fender_left_ae_bottom_0.geometry}
                    material={materials.ae_bottom}
                  />
                  <mesh
                    name="fender_left_ae_headlights_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.fender_left_ae_headlights_0.geometry}
                    material={materials.ae_headlights}
                  />
                </group>
              </group>
              <group name="body" position={[3.111, 29.909, 31.888]}>
                <group name="Object_27" position={[-36.753, 1.278, 30.233]}>
                  <mesh
                    name="body_ae_body_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.body_ae_body_0.geometry}
                    material={materials.ae_body}
                  />
                  <mesh
                    name="body_ae_body_secondary_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.body_ae_body_secondary_0.geometry}
                    material={materials.ae_body_secondary}
                  />
                  <mesh
                    name="body_Material_#1595_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['body_Material_#1595_0'].geometry}
                    material={materials.Material_1595}
                  />
                  <mesh
                    name="body_ae_bottom_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.body_ae_bottom_0.geometry}
                    material={materials.ae_bottom}
                  />
                  <mesh
                    name="body_ae_doorshut_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.body_ae_doorshut_0.geometry}
                    material={materials.ae_doorshut}
                  />
                  <mesh
                    name="body_ae_interior_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.body_ae_interior_0.geometry}
                    material={materials.ae_interior}
                  />
                  <mesh
                    name="body_ae_glass_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.body_ae_glass_0.geometry}
                    material={materials.ae_glass}
                  />
                  <mesh
                    name="body_Material_#2061_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['body_Material_#2061_0'].geometry}
                    material={materials.Material_2061}
                  />
                </group>
              </group>
              <group name="bumper_rear" position={[70.198, 16.97, 31.888]}>
                <group name="Object_37" position={[-103.84, 14.217, 30.233]}>
                  <mesh
                    name="bumper_rear_ae_bottom_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.bumper_rear_ae_bottom_0.geometry}
                    material={materials.ae_bottom}
                  />
                  <mesh
                    name="bumper_rear_ae_body_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.bumper_rear_ae_body_0.geometry}
                    material={materials.ae_body}
                  />
                </group>
              </group>
              <group name="hood" position={[-52.117, 31.557, 31.888]}>
                <group name="Object_41" position={[18.475, -0.37, 30.233]}>
                  <mesh
                    name="hood_ae_body_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.hood_ae_body_0.geometry}
                    material={materials.ae_body}
                  />
                  <mesh
                    name="hood_ae_doorshut_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.hood_ae_doorshut_0.geometry}
                    material={materials.ae_doorshut}
                  />
                </group>
              </group>
              <group name="trunk_door" position={[58.436, 41.584, 31.888]}>
                <group name="Object_45" position={[-92.078, -10.397, 30.233]}>
                  <mesh
                    name="trunk_door_ae_body_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.trunk_door_ae_body_0.geometry}
                    material={materials.ae_body}
                  />
                  <mesh
                    name="trunk_door_ae_doorshut_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.trunk_door_ae_doorshut_0.geometry}
                    material={materials.ae_doorshut}
                  />
                  <mesh
                    name="trunk_door_ae_bottom_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.trunk_door_ae_bottom_0.geometry}
                    material={materials.ae_bottom}
                  />
                  <mesh
                    name="trunk_door_ae_glass_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.trunk_door_ae_glass_0.geometry}
                    material={materials.ae_glass}
                  />
                  <mesh
                    name="trunk_door_Material_#2062_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['trunk_door_Material_#2062_0'].geometry}
                    material={materials.Material_2062}
                  />
                </group>
              </group>
              <group name="bumper_front" position={[-68.828, 18.659, 31.888]}>
                <group name="Object_52" position={[35.186, 12.528, 30.233]}>
                  <mesh
                    name="bumper_front_ae_bottom_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.bumper_front_ae_bottom_0.geometry}
                    material={materials.ae_bottom}
                  />
                  <mesh
                    name="bumper_front_ae_body_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.bumper_front_ae_body_0.geometry}
                    material={materials.ae_body}
                  />
                  <mesh
                    name="bumper_front_ae_headlights_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.bumper_front_ae_headlights_0.geometry}
                    material={materials.ae_headlights}
                  />
                  <mesh
                    name="bumper_front_Material_#2061_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['bumper_front_Material_#2061_0'].geometry}
                    material={materials.Material_2061}
                  />
                </group>
              </group>
              <group name="door_left" position={[-1.058, 31.486, 56.121]}>
                <group name="Object_58" position={[-32.584, -0.299, 5.889]}>
                  <mesh
                    name="door_left_ae_bottom_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.door_left_ae_bottom_0.geometry}
                    material={materials.ae_bottom}
                  />
                  <mesh
                    name="door_left_ae_interior_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.door_left_ae_interior_0.geometry}
                    material={materials.ae_interior}
                  />
                  <mesh
                    name="door_left_ae_body_secondary_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.door_left_ae_body_secondary_0.geometry}
                    material={materials.ae_body_secondary}
                  />
                  <mesh
                    name="door_left_ae_doorshut_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.door_left_ae_doorshut_0.geometry}
                    material={materials.ae_doorshut}
                  />
                  <mesh
                    name="door_left_ae_glass_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.door_left_ae_glass_0.geometry}
                    material={materials.ae_glass}
                  />
                  <mesh
                    name="door_left_ae_body_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.door_left_ae_body_0.geometry}
                    material={materials.ae_body}
                  />
                </group>
              </group>
              <group name="wheel_front_left" position={[-48.172, 15.241, 57.569]} scale={0.35}>
                <group name="Object_66" position={[0.034, 0.152, 10.202]}>
                  <mesh
                    name="wheel_front_left_ae_tier_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.wheel_front_left_ae_tier_0.geometry}
                    material={materials.ae_tier}
                  />
                  <mesh
                    name="wheel_front_left_ae_rim_colour_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.wheel_front_left_ae_rim_colour_0.geometry}
                    material={materials.ae_rim_colour}
                  />
                </group>
              </group>
              <group
                name="headlight_right"
                position={[-72.453, 27.98, 14.369]}
                rotation={[0, 0, -1.588]}>
                <group name="Object_70" position={[37.874, 4.577, 47.549]}>
                  <mesh
                    name="headlight_right_ae_bottom_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.headlight_right_ae_bottom_0.geometry}
                    material={materials.ae_bottom}
                  />
                  <mesh
                    name="headlight_right_ae_glass_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.headlight_right_ae_glass_0.geometry}
                    material={materials.ae_glass}
                  />
                  <mesh
                    name="headlight_right_ae_headlights_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.headlight_right_ae_headlights_0.geometry}
                    material={materials.ae_headlights}
                  />
                  <mesh
                    name="headlight_right_ae_body_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.headlight_right_ae_body_0.geometry}
                    material={materials.ae_body}
                  />
                </group>
              </group>
              <group name="fender_right" position={[-50.498, 22.532, 5.564]}>
                <group name="Object_76" position={[16.856, 8.655, 56.136]}>
                  <mesh
                    name="fender_right_ae_body_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.fender_right_ae_body_0.geometry}
                    material={materials.ae_body}
                  />
                  <mesh
                    name="fender_right_ae_body_secondary_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.fender_right_ae_body_secondary_0.geometry}
                    material={materials.ae_body_secondary}
                  />
                  <mesh
                    name="fender_right_ae_bottom_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.fender_right_ae_bottom_0.geometry}
                    material={materials.ae_bottom}
                  />
                  <mesh
                    name="fender_right_ae_headlights_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.fender_right_ae_headlights_0.geometry}
                    material={materials.ae_headlights}
                  />
                </group>
              </group>
              <group name="backlight_right" position={[79.037, 29.342, 14.193]} scale={1.038}>
                <group name="Object_82" position={[-112.804, 1.925, 46.547]}>
                  <mesh
                    name="backlight_right_ae_bottom_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.backlight_right_ae_bottom_0.geometry}
                    material={materials.ae_bottom}
                  />
                  <mesh
                    name="backlight_right_ae_headlights_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.backlight_right_ae_headlights_0.geometry}
                    material={materials.ae_headlights}
                  />
                </group>
              </group>
              <group name="brakedisk_front_left" position={[-47.762, 15.046, 55.909]} scale={0.35}>
                <group name="Object_86" position={[-1.137, 0.709, 11.754]}>
                  <mesh
                    name="brakedisk_front_left_brakes_1s_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.brakedisk_front_left_brakes_1s_0.geometry}
                    material={materials.brakes_1s}
                  />
                </group>
              </group>
              <group name="brakedisk_front_right" position={[-47.762, 15.046, 4.51]} scale={0.35}>
                <group name="Object_89" position={[-1.137, 0.709, 11.754]}>
                  <mesh
                    name="brakedisk_front_right_brakes_1s_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.brakedisk_front_right_brakes_1s_0.geometry}
                    material={materials.brakes_1s}
                  />
                </group>
              </group>
              <group name="wheel_front_right" position={[-48.172, 15.241, 6.169]} scale={0.35}>
                <group name="Object_92" position={[0.034, 0.152, 10.202]}>
                  <mesh
                    name="wheel_front_right_ae_tier_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.wheel_front_right_ae_tier_0.geometry}
                    material={materials.ae_tier}
                  />
                  <mesh
                    name="wheel_front_right_ae_rim_colour_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.wheel_front_right_ae_rim_colour_0.geometry}
                    material={materials.ae_rim_colour}
                  />
                </group>
              </group>
              <group name="door_right" position={[-1.058, 31.486, 7.605]}>
                <group name="Object_96" position={[-32.584, -0.299, 5.889]}>
                  <mesh
                    name="door_right_ae_bottom_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.door_right_ae_bottom_0.geometry}
                    material={materials.ae_bottom}
                  />
                  <mesh
                    name="door_right_ae_interior_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.door_right_ae_interior_0.geometry}
                    material={materials.ae_interior}
                  />
                  <mesh
                    name="door_right_ae_body_secondary_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.door_right_ae_body_secondary_0.geometry}
                    material={materials.ae_body_secondary}
                  />
                  <mesh
                    name="door_right_ae_doorshut_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.door_right_ae_doorshut_0.geometry}
                    material={materials.ae_doorshut}
                  />
                  <mesh
                    name="door_right_ae_glass_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.door_right_ae_glass_0.geometry}
                    material={materials.ae_glass}
                  />
                  <mesh
                    name="door_right_ae_body_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.door_right_ae_body_0.geometry}
                    material={materials.ae_body}
                  />
                </group>
              </group>
              <group name="brakedisk_rear_right" position={[46.401, 15.046, 4.51]} scale={0.35}>
                <group name="Object_104" position={[-1.137, 0.709, 11.754]}>
                  <mesh
                    name="brakedisk_rear_right_brakes_1s_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.brakedisk_rear_right_brakes_1s_0.geometry}
                    material={materials.brakes_1s}
                  />
                </group>
              </group>
              <group name="wheel_rear_right" position={[45.991, 15.241, 6.169]} scale={0.35}>
                <group name="Object_107" position={[0.034, 0.152, 10.202]}>
                  <mesh
                    name="wheel_rear_right_ae_tier_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.wheel_rear_right_ae_tier_0.geometry}
                    material={materials.ae_tier}
                  />
                  <mesh
                    name="wheel_rear_right_ae_rim_colour_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.wheel_rear_right_ae_rim_colour_0.geometry}
                    material={materials.ae_rim_colour}
                  />
                </group>
              </group>
              <group name="brakedisk_rear_left" position={[46.401, 15.046, 55.909]} scale={0.35}>
                <group name="Object_111" position={[-1.137, 0.709, 11.754]}>
                  <mesh
                    name="brakedisk_rear_left_brakes_1s_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.brakedisk_rear_left_brakes_1s_0.geometry}
                    material={materials.brakes_1s}
                  />
                </group>
              </group>
              <group name="wheel_rear_left" position={[45.991, 15.241, 57.569]} scale={0.35}>
                <group name="Object_114" position={[0.034, 0.152, 10.202]}>
                  <mesh
                    name="wheel_rear_left_ae_tier_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.wheel_rear_left_ae_tier_0.geometry}
                    material={materials.ae_tier}
                  />
                  <mesh
                    name="wheel_rear_left_ae_rim_colour_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.wheel_rear_left_ae_rim_colour_0.geometry}
                    material={materials.ae_rim_colour}
                  />
                </group>
              </group>
              <group name="GRILL" position={[-68.828, 18.659, 31.888]}>
                <group name="Object_118" position={[35.186, 12.528, 30.233]}>
                  <mesh
                    name="GRILL_11_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['GRILL_11_-_Default_0'].geometry}
                    material={materials['11_-_Default']}
                  />
                </group>
              </group>
              <group name="Object001" position={[3.111, 29.909, 31.888]}>
                <group name="Object_121" position={[-36.753, 1.278, 30.233]}>
                  <mesh
                    name="Object001_Material_#2062_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Object001_Material_#2062_0'].geometry}
                    material={materials.Material_2062}
                  />
                </group>
              </group>
              <group name="Object003" position={[-68.828, 18.659, 31.888]}>
                <group name="Object_124" position={[35.186, 12.528, 30.233]}>
                  <mesh
                    name="Object003_ae_bottom_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object003_ae_bottom_0.geometry}
                    material={materials.ae_bottom}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/ae86.glb')
