/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { usePlayerStatesStore } from "@/lib/store";
import { CarModelProps } from "@/lib/types";

type GLTFResult = GLTF & {
  nodes: {
    Body001_1: THREE.Mesh;
    Body001_2: THREE.Mesh;
    FrontLeftWheel001: THREE.Mesh;
    FrontRightWheel001: THREE.Mesh;
    RearLeftWheel001: THREE.Mesh;
    RearRightWheel001: THREE.Mesh;
  };
  materials: {
    ["AKC_Col_1_Tex.001"]: THREE.MeshStandardMaterial;
    ["AKC_Lights_Tex.001"]: THREE.MeshStandardMaterial;
  };
};

export function Model({ playerId, ...props }: CarModelProps) {
  const { nodes, materials } = useGLTF("/models/cars/Daika.glb") as GLTFResult;

  const { registerPlayerWheels } = usePlayerStatesStore();
  const frontLeftWheelRef = useRef<THREE.Mesh>(null);
  const frontRightWheelRef = useRef<THREE.Mesh>(null);
  const rearLeftWheelRef = useRef<THREE.Mesh>(null);
  const rearRightWheelRef = useRef<THREE.Mesh>(null);
  const registrationRef = useRef(false);

  useEffect(() => {
    if (registrationRef.current) return;

    const wheelRefs = {
      FrontLeftWheel: frontLeftWheelRef,
      FrontRightWheel: frontRightWheelRef,
      RearLeftWheel: rearLeftWheelRef,
      RearRightWheel: rearRightWheelRef,
    };

    registerPlayerWheels(playerId, wheelRefs);

    registrationRef.current = true;
  }, []);

  return (
    <group {...props} dispose={null}>
      <group name="Daika" userData={{ name: "Daika" }}>
        <group name="Body001" userData={{ name: "Body.001" }}>
          <mesh
            name="Body001_1"
            castShadow
            receiveShadow
            geometry={nodes.Body001_1.geometry}
            material={materials["AKC_Col_1_Tex.001"]}
          />
          <mesh
            name="Body001_2"
            castShadow
            receiveShadow
            geometry={nodes.Body001_2.geometry}
            material={materials["AKC_Lights_Tex.001"]}
          />
        </group>
        <group name="Meshes001" userData={{ name: "Meshes.001" }}>
          <mesh
            ref={frontLeftWheelRef}
            name="FrontLeftWheel001"
            castShadow
            receiveShadow
            geometry={nodes.FrontLeftWheel001.geometry}
            material={materials["AKC_Col_1_Tex.001"]}
            position={[0.603, 0.322, 1.077]}
            userData={{ name: "FrontLeftWheel.001" }}
          />
          <mesh
            ref={frontRightWheelRef}
            name="FrontRightWheel001"
            castShadow
            receiveShadow
            geometry={nodes.FrontRightWheel001.geometry}
            material={materials["AKC_Col_1_Tex.001"]}
            position={[-0.603, 0.322, 1.077]}
            userData={{ name: "FrontRightWheel.001" }}
          />
          <mesh
            ref={rearLeftWheelRef}
            name="RearLeftWheel001"
            castShadow
            receiveShadow
            geometry={nodes.RearLeftWheel001.geometry}
            material={materials["AKC_Col_1_Tex.001"]}
            position={[0.603, 0.322, -1.17]}
            userData={{ name: "RearLeftWheel.001" }}
          />
          <mesh
            ref={rearRightWheelRef}
            name="RearRightWheel001"
            castShadow
            receiveShadow
            geometry={nodes.RearRightWheel001.geometry}
            material={materials["AKC_Col_1_Tex.001"]}
            position={[-0.603, 0.322, -1.17]}
            userData={{ name: "RearRightWheel.001" }}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/cars/Daika.glb");
