/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { usePlayerStatesStore } from "@/lib/store";
import { CarModelProps } from "@/lib/types";

type GLTFResult = GLTF & {
  nodes: {
    Body002_1: THREE.Mesh;
    Body002_2: THREE.Mesh;
    FrontLeftWheel002: THREE.Mesh;
    FrontRightWheel002: THREE.Mesh;
    RearLeftWheel002: THREE.Mesh;
    RearRightWheel002: THREE.Mesh;
  };
  materials: {
    ["AKC_Col_1_Tex.002"]: THREE.MeshStandardMaterial;
    ["AKC_Lights_Tex.002"]: THREE.MeshStandardMaterial;
  };
};

export function Model({ playerId, ...props }: CarModelProps) {
  const { nodes, materials } = useGLTF("/models/cars/Daishi.glb") as GLTFResult;

  const { registerPlayerWheels } = usePlayerStatesStore();
  const frontLeftWheelRef = useRef<THREE.Mesh>(null);
  const frontRightWheelRef = useRef<THREE.Mesh>(null);
  const rearLeftWheelRef = useRef<THREE.Mesh>(null);
  const rearRightWheelRef = useRef<THREE.Mesh>(null);
  const registrationRef = useRef(false);

  useEffect(() => {
    if (registrationRef.current) return;

    const wheelRefs = {
      FrontLeftWheel: frontLeftWheelRef,
      FrontRightWheel: frontRightWheelRef,
      RearLeftWheel: rearLeftWheelRef,
      RearRightWheel: rearRightWheelRef,
    };

    registerPlayerWheels(playerId, wheelRefs);

    registrationRef.current = true;
  }, []);

  return (
    <group {...props} dispose={null}>
      <group name="Daishi" userData={{ name: "Daishi" }}>
        <group name="Body002" userData={{ name: "Body.002" }}>
          <mesh
            name="Body002_1"
            castShadow
            receiveShadow
            geometry={nodes.Body002_1.geometry}
            material={materials["AKC_Col_1_Tex.002"]}
          />
          <mesh
            name="Body002_2"
            castShadow
            receiveShadow
            geometry={nodes.Body002_2.geometry}
            material={materials["AKC_Lights_Tex.002"]}
          />
        </group>
        <group name="Meshes002" userData={{ name: "Meshes.002" }}>
          <mesh
            ref={frontLeftWheelRef}
            name="FrontLeftWheel002"
            castShadow
            receiveShadow
            geometry={nodes.FrontLeftWheel002.geometry}
            material={materials["AKC_Col_1_Tex.002"]}
            position={[0.602, 0.28, 0.991]}
            userData={{ name: "FrontLeftWheel.002" }}
          />
          <mesh
            ref={frontRightWheelRef}
            name="FrontRightWheel002"
            castShadow
            receiveShadow
            geometry={nodes.FrontRightWheel002.geometry}
            material={materials["AKC_Col_1_Tex.002"]}
            position={[-0.602, 0.28, 0.991]}
            userData={{ name: "FrontRightWheel.002" }}
          />
          <mesh
            ref={rearLeftWheelRef}
            name="RearLeftWheel002"
            castShadow
            receiveShadow
            geometry={nodes.RearLeftWheel002.geometry}
            material={materials["AKC_Col_1_Tex.002"]}
            position={[0.602, 0.28, -0.997]}
            userData={{ name: "RearLeftWheel.002" }}
          />
          <mesh
            ref={rearRightWheelRef}
            name="RearRightWheel002"
            castShadow
            receiveShadow
            geometry={nodes.RearRightWheel002.geometry}
            material={materials["AKC_Col_1_Tex.002"]}
            position={[-0.602, 0.28, -0.997]}
            userData={{ name: "RearRightWheel.002" }}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/cars/Daishi.glb");
