/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Body004_1: THREE.Mesh
    Body004_2: THREE.Mesh
    Spoiler001: THREE.Mesh
    FrontLeftWheel004: THREE.Mesh
    FrontRightWheel004: THREE.Mesh
    RearLeftWheel004: THREE.Mesh
    RearRightWheel004: THREE.Mesh
  }
  materials: {
    ['AKC_Col_1_Tex.004']: THREE.MeshStandardMaterial
    ['AKC_Lights_Tex.004']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/cars/Ouki.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Ouki" userData={{ name: 'Ouki' }}>
        <group name="Body004" userData={{ name: 'Body.004' }}>
          <mesh
            name="Body004_1"
            castShadow
            receiveShadow
            geometry={nodes.Body004_1.geometry}
            material={materials['AKC_Col_1_Tex.004']}
          />
          <mesh
            name="Body004_2"
            castShadow
            receiveShadow
            geometry={nodes.Body004_2.geometry}
            material={materials['AKC_Lights_Tex.004']}
          />
        </group>
        <mesh
          name="Spoiler001"
          castShadow
          receiveShadow
          geometry={nodes.Spoiler001.geometry}
          material={materials['AKC_Col_1_Tex.004']}
          position={[0, 1.033, -1.705]}
          userData={{ name: 'Spoiler.001' }}
        />
        <group name="Meshes004" userData={{ name: 'Meshes.004' }}>
          <mesh
            name="FrontLeftWheel004"
            castShadow
            receiveShadow
            geometry={nodes.FrontLeftWheel004.geometry}
            material={materials['AKC_Col_1_Tex.004']}
            position={[0.613, 0.287, 1.055]}
            userData={{ name: 'FrontLeftWheel.004' }}
          />
          <mesh
            name="FrontRightWheel004"
            castShadow
            receiveShadow
            geometry={nodes.FrontRightWheel004.geometry}
            material={materials['AKC_Col_1_Tex.004']}
            position={[-0.613, 0.287, 1.055]}
            userData={{ name: 'FrontRightWheel.004' }}
          />
          <mesh
            name="RearLeftWheel004"
            castShadow
            receiveShadow
            geometry={nodes.RearLeftWheel004.geometry}
            material={materials['AKC_Col_1_Tex.004']}
            position={[0.62, 0.287, -1.055]}
            userData={{ name: 'RearLeftWheel.004' }}
          />
          <mesh
            name="RearRightWheel004"
            castShadow
            receiveShadow
            geometry={nodes.RearRightWheel004.geometry}
            material={materials['AKC_Col_1_Tex.004']}
            position={[-0.62, 0.287, -1.055]}
            userData={{ name: 'RearRightWheel.004' }}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/cars/Ouki.glb')
