/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        Body_1: THREE.Mesh;
        Body_2: THREE.Mesh;
        Spoiler: THREE.Mesh;
        Vinyls: THREE.Mesh;
        FrontLeftWheel: THREE.Mesh;
        FrontRightWheel: THREE.Mesh;
        RearLeftWheel: THREE.Mesh;
        RearRightWheel: THREE.Mesh;
    };
    materials: {
        AKC_Col_1_Tex: THREE.MeshStandardMaterial;
        AKC_Lights_Tex: THREE.MeshStandardMaterial;
        AKC_Vinyls_Mat: THREE.MeshStandardMaterial;
    };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
    const { nodes, materials } = useGLTF(
        "/models/cars/Renzo.glb"
    ) as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <group
                name="Renzo_1"
                position={[-4.964, 0, 2.49]}
                userData={{ name: "Renzo" }}
            >
                <group name="Body" userData={{ name: "Body" }}>
                    <mesh
                        name="Body_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Body_1.geometry}
                        material={materials.AKC_Col_1_Tex}
                    />
                    <mesh
                        name="Body_2"
                        castShadow
                        receiveShadow
                        geometry={nodes.Body_2.geometry}
                        material={materials.AKC_Lights_Tex}
                    />
                </group>
                <mesh
                    name="Spoiler"
                    castShadow
                    receiveShadow
                    geometry={nodes.Spoiler.geometry}
                    material={materials.AKC_Col_1_Tex}
                    position={[0, 0.901, -1.544]}
                    userData={{ name: "Spoiler" }}
                />
                <mesh
                    name="Vinyls"
                    castShadow
                    receiveShadow
                    geometry={nodes.Vinyls.geometry}
                    material={materials.AKC_Vinyls_Mat}
                    userData={{ name: "Vinyls" }}
                />
                <group name="Meshes" userData={{ name: "Meshes" }}>
                    <mesh
                        name="FrontLeftWheel"
                        castShadow
                        receiveShadow
                        geometry={nodes.FrontLeftWheel.geometry}
                        material={materials.AKC_Col_1_Tex}
                        position={[0.663, 0.288, 1.084]}
                        userData={{ name: "FrontLeftWheel" }}
                    />
                    <mesh
                        name="FrontRightWheel"
                        castShadow
                        receiveShadow
                        geometry={nodes.FrontRightWheel.geometry}
                        material={materials.AKC_Col_1_Tex}
                        position={[-0.663, 0.288, 1.084]}
                        userData={{ name: "FrontRightWheel" }}
                    />
                    <mesh
                        name="RearLeftWheel"
                        castShadow
                        receiveShadow
                        geometry={nodes.RearLeftWheel.geometry}
                        material={materials.AKC_Col_1_Tex}
                        position={[0.664, 0.3, -1.153]}
                        userData={{ name: "RearLeftWheel" }}
                    />
                    <mesh
                        name="RearRightWheel"
                        castShadow
                        receiveShadow
                        geometry={nodes.RearRightWheel.geometry}
                        material={materials.AKC_Col_1_Tex}
                        position={[-0.664, 0.3, -1.153]}
                        userData={{ name: "RearRightWheel" }}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/models/cars/Renzo.glb");
