/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Body005_1: THREE.Mesh
    Body005_2: THREE.Mesh
    Spoiler002: THREE.Mesh
    Vinyls: THREE.Mesh
    FrontLeftWheel005: THREE.Mesh
    FrontRightWheel005: THREE.Mesh
    RearLeftWheel005: THREE.Mesh
    RearRightWheel005: THREE.Mesh
  }
  materials: {
    ['AKC_Col_1_Tex.005']: THREE.MeshStandardMaterial
    ['AKC_Lights_Tex.005']: THREE.MeshStandardMaterial
    AKC_Vinyls_Mat: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/cars/Renzo.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Renzo" userData={{ name: 'Renzo' }}>
        <group name="Body005" userData={{ name: 'Body.005' }}>
          <mesh
            name="Body005_1"
            castShadow
            receiveShadow
            geometry={nodes.Body005_1.geometry}
            material={materials['AKC_Col_1_Tex.005']}
          />
          <mesh
            name="Body005_2"
            castShadow
            receiveShadow
            geometry={nodes.Body005_2.geometry}
            material={materials['AKC_Lights_Tex.005']}
          />
        </group>
        <mesh
          name="Spoiler002"
          castShadow
          receiveShadow
          geometry={nodes.Spoiler002.geometry}
          material={materials['AKC_Col_1_Tex.005']}
          position={[0, 0.901, -1.544]}
          userData={{ name: 'Spoiler.002' }}
        />
        <mesh
          name="Vinyls"
          castShadow
          receiveShadow
          geometry={nodes.Vinyls.geometry}
          material={materials.AKC_Vinyls_Mat}
          userData={{ name: 'Vinyls' }}
        />
        <group name="Meshes005" userData={{ name: 'Meshes.005' }}>
          <mesh
            name="FrontLeftWheel005"
            castShadow
            receiveShadow
            geometry={nodes.FrontLeftWheel005.geometry}
            material={materials['AKC_Col_1_Tex.005']}
            position={[0.663, 0.288, 1.084]}
            userData={{ name: 'FrontLeftWheel.005' }}
          />
          <mesh
            name="FrontRightWheel005"
            castShadow
            receiveShadow
            geometry={nodes.FrontRightWheel005.geometry}
            material={materials['AKC_Col_1_Tex.005']}
            position={[-0.663, 0.288, 1.084]}
            userData={{ name: 'FrontRightWheel.005' }}
          />
          <mesh
            name="RearLeftWheel005"
            castShadow
            receiveShadow
            geometry={nodes.RearLeftWheel005.geometry}
            material={materials['AKC_Col_1_Tex.005']}
            position={[0.664, 0.3, -1.153]}
            userData={{ name: 'RearLeftWheel.005' }}
          />
          <mesh
            name="RearRightWheel005"
            castShadow
            receiveShadow
            geometry={nodes.RearRightWheel005.geometry}
            material={materials['AKC_Col_1_Tex.005']}
            position={[-0.664, 0.3, -1.153]}
            userData={{ name: 'RearRightWheel.005' }}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/cars/Renzo.glb')
