/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Body006_1: THREE.Mesh
    Body006_2: THREE.Mesh
    FrontBumper: THREE.Mesh
    TopLights_1: THREE.Mesh
    TopLights_2: THREE.Mesh
    Vinyls001: THREE.Mesh
    FrontLeftWheel006: THREE.Mesh
    FrontRightWheel006: THREE.Mesh
    RearLeftWheel006: THREE.Mesh
    RearRightWheel006: THREE.Mesh
  }
  materials: {
    ['AKC_Col_1_Tex.006']: THREE.MeshStandardMaterial
    ['AKC_Lights_Tex.006']: THREE.MeshStandardMaterial
    ['AKC_Vinyls_Mat.001']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/cars/Sadako.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Sadako" userData={{ name: 'Sadako' }}>
        <group name="Body006" userData={{ name: 'Body.006' }}>
          <mesh
            name="Body006_1"
            castShadow
            receiveShadow
            geometry={nodes.Body006_1.geometry}
            material={materials['AKC_Col_1_Tex.006']}
          />
          <mesh
            name="Body006_2"
            castShadow
            receiveShadow
            geometry={nodes.Body006_2.geometry}
            material={materials['AKC_Lights_Tex.006']}
          />
        </group>
        <mesh
          name="FrontBumper"
          castShadow
          receiveShadow
          geometry={nodes.FrontBumper.geometry}
          material={materials['AKC_Col_1_Tex.006']}
          position={[0, 0.506, 1.59]}
          userData={{ name: 'FrontBumper' }}
        />
        <group name="TopLights" position={[0, 1.359, -0.016]} userData={{ name: 'TopLights' }}>
          <mesh
            name="TopLights_1"
            castShadow
            receiveShadow
            geometry={nodes.TopLights_1.geometry}
            material={materials['AKC_Col_1_Tex.006']}
          />
          <mesh
            name="TopLights_2"
            castShadow
            receiveShadow
            geometry={nodes.TopLights_2.geometry}
            material={materials['AKC_Lights_Tex.006']}
          />
        </group>
        <mesh
          name="Vinyls001"
          castShadow
          receiveShadow
          geometry={nodes.Vinyls001.geometry}
          material={materials['AKC_Vinyls_Mat.001']}
          userData={{ name: 'Vinyls.001' }}
        />
        <group name="Meshes006" userData={{ name: 'Meshes.006' }}>
          <mesh
            name="FrontLeftWheel006"
            castShadow
            receiveShadow
            geometry={nodes.FrontLeftWheel006.geometry}
            material={materials['AKC_Col_1_Tex.006']}
            position={[0.563, 0.28, 1.12]}
            userData={{ name: 'FrontLeftWheel.006' }}
          />
          <mesh
            name="FrontRightWheel006"
            castShadow
            receiveShadow
            geometry={nodes.FrontRightWheel006.geometry}
            material={materials['AKC_Col_1_Tex.006']}
            position={[-0.563, 0.28, 1.12]}
            userData={{ name: 'FrontRightWheel.006' }}
          />
          <mesh
            name="RearLeftWheel006"
            castShadow
            receiveShadow
            geometry={nodes.RearLeftWheel006.geometry}
            material={materials['AKC_Col_1_Tex.006']}
            position={[0.563, 0.28, -1.212]}
            userData={{ name: 'RearLeftWheel.006' }}
          />
          <mesh
            name="RearRightWheel006"
            castShadow
            receiveShadow
            geometry={nodes.RearRightWheel006.geometry}
            material={materials['AKC_Col_1_Tex.006']}
            position={[-0.563, 0.28, -1.212]}
            userData={{ name: 'RearRightWheel.006' }}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/cars/Sadako.glb')
