/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
    nodes: {
        Body_1: THREE.Mesh;
        Body_2: THREE.Mesh;
        FrontBumper: THREE.Mesh;
        TopLights_1: THREE.Mesh;
        TopLights_2: THREE.Mesh;
        Vinyls: THREE.Mesh;
        FrontLeftWheel: THREE.Mesh;
        FrontRightWheel: THREE.Mesh;
        RearLeftWheel: THREE.Mesh;
        RearRightWheel: THREE.Mesh;
    };
    materials: {
        AKC_Col_1_Tex: THREE.MeshStandardMaterial;
        AKC_Lights_Tex: THREE.MeshStandardMaterial;
        AKC_Vinyls_Mat: THREE.MeshStandardMaterial;
    };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
    const { nodes, materials } = useGLTF(
        "/models/cars/Sadako.glb"
    ) as GLTFResult;
    return (
        <group {...props} dispose={null}>
            <group
                name="Sadako_1"
                position={[-0.8, 0, 2.71]}
                userData={{ name: "Sadako" }}
            >
                <group name="Body" userData={{ name: "Body" }}>
                    <mesh
                        name="Body_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.Body_1.geometry}
                        material={materials.AKC_Col_1_Tex}
                    />
                    <mesh
                        name="Body_2"
                        castShadow
                        receiveShadow
                        geometry={nodes.Body_2.geometry}
                        material={materials.AKC_Lights_Tex}
                    />
                </group>
                <mesh
                    name="FrontBumper"
                    castShadow
                    receiveShadow
                    geometry={nodes.FrontBumper.geometry}
                    material={materials.AKC_Col_1_Tex}
                    position={[0, 0.506, 1.59]}
                    userData={{ name: "FrontBumper" }}
                />
                <group
                    name="TopLights"
                    position={[0, 1.359, -0.016]}
                    userData={{ name: "TopLights" }}
                >
                    <mesh
                        name="TopLights_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.TopLights_1.geometry}
                        material={materials.AKC_Col_1_Tex}
                    />
                    <mesh
                        name="TopLights_2"
                        castShadow
                        receiveShadow
                        geometry={nodes.TopLights_2.geometry}
                        material={materials.AKC_Lights_Tex}
                    />
                </group>
                <mesh
                    name="Vinyls"
                    castShadow
                    receiveShadow
                    geometry={nodes.Vinyls.geometry}
                    material={materials.AKC_Vinyls_Mat}
                    userData={{ name: "Vinyls" }}
                />
                <group name="Meshes" userData={{ name: "Meshes" }}>
                    <mesh
                        name="FrontLeftWheel"
                        castShadow
                        receiveShadow
                        geometry={nodes.FrontLeftWheel.geometry}
                        material={materials.AKC_Col_1_Tex}
                        position={[0.563, 0.28, 1.12]}
                        userData={{ name: "FrontLeftWheel" }}
                    />
                    <mesh
                        name="FrontRightWheel"
                        castShadow
                        receiveShadow
                        geometry={nodes.FrontRightWheel.geometry}
                        material={materials.AKC_Col_1_Tex}
                        position={[-0.563, 0.28, 1.12]}
                        userData={{ name: "FrontRightWheel" }}
                    />
                    <mesh
                        name="RearLeftWheel"
                        castShadow
                        receiveShadow
                        geometry={nodes.RearLeftWheel.geometry}
                        material={materials.AKC_Col_1_Tex}
                        position={[0.563, 0.28, -1.212]}
                        userData={{ name: "RearLeftWheel" }}
                    />
                    <mesh
                        name="RearRightWheel"
                        castShadow
                        receiveShadow
                        geometry={nodes.RearRightWheel.geometry}
                        material={materials.AKC_Col_1_Tex}
                        position={[-0.563, 0.28, -1.212]}
                        userData={{ name: "RearRightWheel" }}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/models/cars/Sadako.glb");
